import Providers from "@/components/Providers";
import "./globals.css";
import AppBar from "@/components/AppBar";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Next-Auth",
  description: "Generated by Mykola Maslakai",
};

interface Props {
  children: React.ReactNode;
}

export default function RootLayout(props: Props) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <Providers>
          <AppBar />
          <main className="flex-grow">{props.children}</main>
          <ToastContainer />
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
